### ISSUE TITLE
Error frame_processor

### ISSUE THREAD

**Issue by samuelrubiodev** [wandaweb/Facefusion-Sagemaker-Studio-Lab#1]
I got the following error after starting the server with zrok:

Traceback (most recent call last):
  File "/home/studio-lab-user/Facefusion-Sagemaker-Studio-Lab/facefusion/run.py", line 6, in <module>
    core.cli()
  File "/home/studio-lab-user/Facefusion-Sagemaker-Studio-Lab/facefusion/facefusion/core.py", line 84, in cli
    frame_processor_module = load_frame_processor_module(frame_processor)
  File "/home/studio-lab-user/Facefusion-Sagemaker-Studio-Lab/facefusion/facefusion/processors/frame/core.py", line 35, in load_frame_processor_module
    frame_processor_module = importlib.import_module('facefusion.processors.frame.modules.' + frame_processor)
  File "/home/studio-lab-user/.conda/envs/facefusion/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/studio-lab-user/Facefusion-Sagemaker-Studio-Lab/facefusion/facefusion/processors/frame/modules/frame_enhancer.py", line 5, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "/home/studio-lab-user/.conda/envs/facefusion/lib/python3.10/site-packages/basicsr/__init__.py", line 3, in <module>
    from .archs import *
  File "/home/studio-lab-user/.conda/envs/facefusion/lib/python3.10/site-packages/basicsr/archs/__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "/home/studio-lab-user/.conda/envs/facefusion/lib/python3.10/site-packages/basicsr/utils/__init__.py", line 2, in <module>
    from .diffjpeg import DiffJPEG
  File "/home/studio-lab-user/.conda/envs/facefusion/lib/python3.10/site-packages/basicsr/utils/diffjpeg.py", line 19, in <module>
    y_table = nn.Parameter(torch.from_numpy(y_table))
TypeError: expected np.ndarray (got numpy.ndarray)

**Comment by wandaweb** [comment]
Thanks for the issue. It's fixed in the latest update

**Comment by samuelrubiodev** [comment]
Thanks
